import { Image, Tag } from 'antd'

const tagColumn = (title, dataIndex, colors = {}) => ({
  title,
  dataIndex,
  render: (value) => value ? <Tag color={colors[value] || 'blue'}>{value}</Tag> : '-',
})

export const pageConfigs = [
  {
    path: 'cats',
    title: '猫咪档案',
    resource: 'cats',
    searchPlaceholder: '搜索猫咪名称',
    filters: [
      { name: 'health_status', placeholder: '健康状态', options: ['健康', '观察中', '治疗中'] },
      { name: 'adoption_status', placeholder: '领养状态', options: ['待领养', '已领养', '暂不开放'] },
    ],
    fields: [
      { name: 'name', label: '猫咪名称', required: true },
      { name: 'gender', label: '性别', type: 'select', options: ['公', '母', '未知'] },
      { name: 'age', label: '年龄' },
      { name: 'color', label: '毛色' },
      { name: 'breed', label: '品种' },
      { name: 'campus_area', label: '活动区域' },
      { name: 'health_status', label: '健康状态', type: 'select', options: ['健康', '观察中', '治疗中'] },
      { name: 'sterilized', label: '是否绝育', type: 'select', options: ['是', '否', '未知'] },
      { name: 'adoption_status', label: '领养状态', type: 'select', options: ['待领养', '已领养', '暂不开放'] },
      { name: 'photo', label: '照片链接' },
      { name: 'personality', label: '性格描述' },
      { name: 'description', label: '备注描述', type: 'textarea' },
    ],
    columns: [
      { title: '照片', dataIndex: 'photo', render: (value) => value ? <Image src={value} className="cat-photo" /> : '-' },
      { title: '名称', dataIndex: 'name' },
      { title: '性别', dataIndex: 'gender' },
      { title: '年龄', dataIndex: 'age' },
      { title: '区域', dataIndex: 'campus_area' },
      tagColumn('健康状态', 'health_status', { 健康: 'green', 观察中: 'orange', 治疗中: 'red' }),
      tagColumn('领养状态', 'adoption_status', { 待领养: 'gold', 已领养: 'green', 暂不开放: 'default' }),
    ],
  },
  {
    path: 'health',
    title: '健康管理',
    resource: 'health-records',
    searchPlaceholder: '搜索猫咪名称',
    filters: [
      { name: 'record_type', placeholder: '记录类型', options: ['体检', '疫苗', '驱虫', '绝育', '受伤', '治疗', '复查'] },
      { name: 'status', placeholder: '处理状态', options: ['待处理', '处理中', '已完成'] },
    ],
    fields: [
      { name: 'cat_id', label: '猫咪ID', type: 'number' },
      { name: 'cat_name', label: '猫咪名称' },
      { name: 'record_type', label: '记录类型', type: 'select', options: ['体检', '疫苗', '驱虫', '绝育', '受伤', '治疗', '复查'], required: true },
      { name: 'record_date', label: '记录日期', type: 'date' },
      { name: 'symptom', label: '症状描述' },
      { name: 'treatment', label: '处理方式', type: 'textarea' },
      { name: 'hospital', label: '医院/机构' },
      { name: 'cost', label: '费用', type: 'number' },
      { name: 'status', label: '处理状态', type: 'select', options: ['待处理', '处理中', '已完成'] },
      { name: 'remark', label: '备注', type: 'textarea' },
    ],
    columns: [
      { title: '猫咪', dataIndex: 'cat_name' },
      tagColumn('类型', 'record_type'),
      { title: '日期', dataIndex: 'record_date' },
      { title: '处理方式', dataIndex: 'treatment' },
      { title: '费用', dataIndex: 'cost' },
      tagColumn('状态', 'status', { 待处理: 'orange', 处理中: 'blue', 已完成: 'green' }),
    ],
  },
  {
    path: 'adoptions',
    title: '猫咪领养',
    resource: 'adoptions',
    searchPlaceholder: '搜索申请人或猫咪',
    filters: [{ name: 'status', placeholder: '审核状态', options: ['待审核', '已通过', '已拒绝'] }],
    fields: [
      { name: 'cat_id', label: '猫咪ID', type: 'number' },
      { name: 'cat_name', label: '猫咪名称' },
      { name: 'applicant_name', label: '申请人', required: true },
      { name: 'student_no', label: '学号' },
      { name: 'phone', label: '联系方式' },
      { name: 'college', label: '学院' },
      { name: 'reason', label: '申请理由', type: 'textarea' },
      { name: 'experience', label: '养宠经验', type: 'textarea' },
      { name: 'status', label: '审核状态', type: 'select', options: ['待审核', '已通过', '已拒绝'] },
      { name: 'apply_time', label: '申请时间', type: 'date' },
      { name: 'review_remark', label: '审核备注', type: 'textarea' },
    ],
    columns: [
      { title: '猫咪', dataIndex: 'cat_name' },
      { title: '申请人', dataIndex: 'applicant_name' },
      { title: '学号', dataIndex: 'student_no' },
      { title: '联系方式', dataIndex: 'phone' },
      tagColumn('状态', 'status', { 待审核: 'orange', 已通过: 'green', 已拒绝: 'red' }),
      { title: '申请时间', dataIndex: 'apply_time' },
    ],
  },
  {
    path: 'community',
    title: '动态社区',
    resource: 'posts',
    searchPlaceholder: '搜索动态标题',
    filters: [
      { name: 'category', placeholder: '动态分类', options: ['日常动态', '寻猫启事', '救助公告', '领养宣传', '活动通知'] },
      { name: 'status', placeholder: '状态', options: ['显示', '隐藏'] },
    ],
    fields: [
      { name: 'title', label: '标题', required: true },
      { name: 'content', label: '内容', type: 'textarea' },
      { name: 'publisher', label: '发布人' },
      { name: 'category', label: '分类', type: 'select', options: ['日常动态', '寻猫启事', '救助公告', '领养宣传', '活动通知'] },
      { name: 'images', label: '图片链接' },
      { name: 'likes', label: '点赞数', type: 'number' },
      { name: 'status', label: '状态', type: 'select', options: ['显示', '隐藏'] },
    ],
    columns: [
      { title: '标题', dataIndex: 'title' },
      { title: '发布人', dataIndex: 'publisher' },
      tagColumn('分类', 'category'),
      { title: '点赞', dataIndex: 'likes' },
      tagColumn('状态', 'status', { 显示: 'green', 隐藏: 'default' }),
    ],
  },
  {
    path: 'supplies',
    title: '物资管理',
    resource: 'supplies',
    searchPlaceholder: '搜索物资名称',
    filters: [
      { name: 'category', placeholder: '物资分类', options: ['猫粮', '猫砂', '药品', '清洁用品', '笼具', '其他'] },
      { name: 'status', placeholder: '库存状态', options: ['充足', '偏少', '短缺'] },
    ],
    fields: [
      { name: 'name', label: '物资名称', required: true },
      { name: 'category', label: '分类', type: 'select', options: ['猫粮', '猫砂', '药品', '清洁用品', '笼具', '其他'] },
      { name: 'quantity', label: '数量', type: 'number' },
      { name: 'unit', label: '单位' },
      { name: 'source', label: '来源' },
      { name: 'storage_location', label: '存放位置' },
      { name: 'status', label: '状态', type: 'select', options: ['充足', '偏少', '短缺'] },
      { name: 'remark', label: '备注', type: 'textarea' },
    ],
    columns: [
      { title: '物资名称', dataIndex: 'name' },
      tagColumn('分类', 'category'),
      { title: '数量', dataIndex: 'quantity' },
      { title: '单位', dataIndex: 'unit' },
      { title: '存放位置', dataIndex: 'storage_location' },
      tagColumn('状态', 'status', { 充足: 'green', 偏少: 'orange', 短缺: 'red' }),
    ],
  },
  {
    path: 'donations',
    title: '爱心捐助',
    resource: 'donations',
    searchPlaceholder: '搜索捐助人',
    filters: [{ name: 'donation_type', placeholder: '捐助类型', options: ['资金', '物资', '其他'] }],
    fields: [
      { name: 'donor_name', label: '捐助人', required: true },
      { name: 'donation_type', label: '捐助类型', type: 'select', options: ['资金', '物资', '其他'] },
      { name: 'amount', label: '金额', type: 'number' },
      { name: 'material_name', label: '物资名称' },
      { name: 'quantity', label: '物资数量', type: 'number' },
      { name: 'donation_date', label: '捐助日期', type: 'date' },
      { name: 'contact', label: '联系方式' },
      { name: 'remark', label: '备注', type: 'textarea' },
    ],
    columns: [
      { title: '捐助人', dataIndex: 'donor_name' },
      tagColumn('类型', 'donation_type', { 资金: 'green', 物资: 'blue', 其他: 'default' }),
      { title: '金额', dataIndex: 'amount' },
      { title: '物资', dataIndex: 'material_name' },
      { title: '数量', dataIndex: 'quantity' },
      { title: '日期', dataIndex: 'donation_date' },
    ],
  },
]
